[package]
name = "token_metadata_local"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.7.11"
borsh = "0.9.1"
spl-token = "3.2.0"