[programs.localnet]
pda_mint = "85185DcWJF1fg7qnAjGnXVf6RU9fPKxCagJ7w1rFxkps"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
